### ISSUE TITLE
Not compatible with mac

### ISSUE THREAD

**Issue by dhwanb** [Antecer/AmusingKeypad#10]
Hi dear 

I have keypads 
use to ch558L chipset 

I set up the device in win10.

It works fine in win10.

But it doesn't work on mac os.

Can you solve this problem ??

Thank you.

**Comment by Antecer** [comment]
Sorry, i don't know what happend, because i don't have mac device.
Some people tell me it work fine, but another tell me can't work.
I see that some people use wine will make it work fine, maybe it can help you?

**Comment by dhwanb** [comment]
Thank you for your answer.

I see that some people use wine will
-> What is wine?

Thank you.

**Comment by Antecer** [comment]
A program that can run "exe" on mac
