### ISSUE TITLE
Winkey + "x" on android not recognized

### ISSUE THREAD

**Issue by Genexix** [Antecer/AmusingKeypad#11]
Hello, 

Shortcut with the winkey is not recognized as a keyboard key press.

**Comment by Antecer** [comment]
What is the function of this key combination, I use some different keyboards to test it on my android phone, didn't see anything happend.

**Comment by Genexix** [comment]
Here are some key combo's

Windows+C = Contacts
Windows+G = Gmail
Windows+L = Calendar
Windows+P = Play Music
Windows+Y = YouTube
Windows+M = Maps

**Comment by Antecer** [comment]
I just test Win+R , it works normal on windows.

**Comment by Antecer** [comment]
@Genexix 
I just test key combo's on my android phone with my 104 keyboard.
But nothing happend!
Can you take a video about them key combo's that works normal on your android device?
