### ISSUE TITLE
Keys not registering after a driver update

### ISSUE THREAD

**Issue by WrixesDog** [Antecer/AmusingKeypad#12]
Keys not registering after a driver update

**Comment by Antecer** [comment]
Please describe in detail what happened to the fault and the state of the keyboard's light after the fault occurred.

**Comment by delcol431** [comment]
It just happened to me too, it's not a firmware problem. It's because by default the keypress moves the cursor to (X=0, Y=0). To solve it, just press on Clear Point
![immagine](https://user-images.githubusercontent.com/62657904/78163973-5e322280-7449-11ea-9669-24ae29c4906e.png)

**Comment by Patrickzize** [comment]
my key are not registered i cant press anything on the keypad, can anyone help me fix this problem?
