### ISSUE TITLE
Device Not Updating Firmware

### ISSUE THREAD

**Issue by NiroMRX** [Antecer/AmusingKeypad#13]
So i tried to change the keybindings on my 2k device, but it said the firmware was not in the latest version, so when i would click yes to update, it just sits there for hours blinking red and i have no idea why it wont update.

**Comment by Antecer** [comment]
![image](https://user-images.githubusercontent.com/8684916/78221975-f4705200-74f6-11ea-96ce-772eab8c6b54.png)
![image](https://user-images.githubusercontent.com/8684916/78221986-fa663300-74f6-11ea-81c9-e8eba5945ea0.png)
![image](https://user-images.githubusercontent.com/8684916/78222013-06ea8b80-74f7-11ea-8f3e-b7127d5ad6dd.png)

**Comment by NiroMRX** [comment]
Ive never seen this on my screen, it just starts blinking red and dosent stop 
![image](https://user-images.githubusercontent.com/63031604/78263739-f969dd00-74c7-11ea-93f1-3fa5b3f48afb.png)
The other 2 for actually updating it i can get to, but then i dont see that its actually updating.

**Comment by NiroMRX** [comment]
I've been letting it sit and blink to see if something would happen if I kept waiting for about 4 hours now and I just realized that it's blinking faster than when it started. I don't know if that has to do with anything, but that's what's happening

**Comment by Antecer** [comment]
Please try to run the application with administrator privileges, this will open debugging information, maybe we can see what is happening.
