### ISSUE TITLE
BackLed "AnyPressOn" and "AnyPressOff" Not Functioning Properly

### ISSUE THREAD

**Issue by Aleyx4** [Antecer/AmusingKeypad#14]
Programming the backleds to "AnyPressOn" sets the backleds are always on while if you program them to "AnyPressOff" the backleds are always off.
![image](https://user-images.githubusercontent.com/19956309/102806822-2c6c3d80-4383-11eb-8a77-0086f8e587e3.png)

**Comment by Antecer** [comment]
Will be fixed in the next firmware version.
