### ISSUE TITLE
Can't update Firmware / App won't let me configure keys

### ISSUE THREAD

**Issue by xFooL** [Antecer/AmusingKeypad#15]
I had to reinstall most of my programms, including my KeypadPro App. I wanted to rebind my keys but the most recent version just says this: 

![image_2021-01-24_192040](https://user-images.githubusercontent.com/30410157/105639534-3a791680-5e79-11eb-9ee3-2fd364f16dec.png)

It didn't let me update the Firmware (crashed after clicking "Update to selected version" after a few seconds) and now it doesn't even let me choose a Release version. 

![image_2021-01-24_192518](https://user-images.githubusercontent.com/30410157/105639667-e02c8580-5e79-11eb-991c-c828988aabaf.png)

I tried older App versions but they won't let me reconfigure my keys (which are now stuck at the factory settings).

**Comment by Antecer** [comment]
Did you try download the last version? you can download from here: https://antecer.com
I think it will not show the Dialog.
Your app didn't show firmware list, May be because it cannot connect to the network.

**Comment by xFooL** [comment]
I redownloaded it and run it as administrator and it worked! Thanks!
