### ISSUE TITLE
Not functioning button

### ISSUE THREAD

**Issue by BalintIstvan0917** [Antecer/AmusingKeypad#16]
I've been using the AmusingPro keypad for well over two years now and just today one of the key didn't function anymore.
I tried the following:

* Re-plugged the cable/tried a different cable
* Swapped multiple switches
* Reinstalled drivers

None of them seem to have worked so I'm stuck with only one button that works. Do you think it can be fixed somehow or do I have to buy a new one?

**Comment by Antecer** [comment]
You need to unscrew it, and then install the switch on the PCB, then you can see if the switch connector is badly soldered.
If the switch connector is jacked up, then you need to re-solder it, you can do it yourself, or find home appliance repair or mobile phone repair.

**Comment by BalintIstvan0917** [comment]
I've re-soldered the connector which solved the problem. Thanks for the quick response!
