### ISSUE TITLE
Keypad won't work after trying to change the LED colours.

### ISSUE THREAD

**Issue by FloMatt1** [Antecer/AmusingKeypad#19]
As stated in the title, i downloaded the latest driver, tried to change the led colours and now the whole keypad won't work anymore. The colours are stuck on what looks like random. I tried replugging it and switching the USB port. I tried resetting the configs via the driver and that didn't work either. I just got the keypad today so i doubt it's a soldering issue. Trying to switch the LED colours does light them up, but it doesn't solve the issue.

**Comment by Antecer** [comment]
I think you need use the last version of app update your firmware.
The last device ver will be 3.0.0.3
![image](https://user-images.githubusercontent.com/8684916/152004714-3fe7c590-e0f6-44f4-8f41-6cc1c75784f7.png)

**Comment by FloMatt1** [comment]
This is what my driver shows, could you send me a local file to update it through ?

![image](https://user-images.githubusercontent.com/98830531/152005657-79b9d7fb-7512-4d8f-ab30-5e97bf3e01ff.png)

**Comment by Antecer** [comment]
wait, i need know, your app version?
The last app version is 3.0.0.9, you can see it in About.

**Comment by FloMatt1** [comment]
My version is 2.0.0.8

**Comment by Antecer** [comment]
> My version is 2.0.0.8

That's the problem!
You need download the app from: https://antecer.com

**Comment by FloMatt1** [comment]
Thanks a lot! There's a lot of places where you can get the driver apparently, never thought of going to your personal website for it. It works fine now <3
