### ISSUE TITLE
Back LED B3 Crash

### ISSUE THREAD

**Issue by EvanSux** [Antecer/AmusingKeypad#3]
Back LED B3. When confirming changes on color under AnyPressFreqColor it crashes the app.

Software v 1.3.2.3
Firmware v 1.3.0.5

**Comment by Antecer** [comment]
@EvanSux I try it, but the app not crashed. 
Can you take a screenshot of each step, including the crash interface.

**Comment by EvanSux** [comment]
![screenshot 45](https://user-images.githubusercontent.com/40912417/42415128-c502e68c-81f9-11e8-8e29-d345cf603fd4.jpg)
![screenshot 46](https://user-images.githubusercontent.com/40912417/42415129-c525d99e-81f9-11e8-978a-f2acaf29a4fa.jpg)
![screenshot 47](https://user-images.githubusercontent.com/40912417/42415130-c5471a00-81f9-11e8-99ed-1f4c9abe13e4.jpg)
![screenshot 48](https://user-images.githubusercontent.com/40912417/42415131-c5687e16-81f9-11e8-9388-bed8fea73d75.jpg)

In AnyPressFreqColor mode all the colors for B3 default to #FFFFFF. Even if factory reset from settings menu.
Other color modes for B3 work as intended.

**Comment by Antecer** [comment]
I tried it many times according to your screenshot steps and everything worked fine.
And i can't find any error code of your images.
Do you test AnyPressFreqColor mode of B1 or B2 or B4, whether the application will also crash?

Maybe you need to tell me what version of the system you are using.

**Comment by EvanSux** [comment]
Just tested the others. Changing the color for AnyPressFreqColor B1, B2, B4 also crashes it.
I'm running Windows 8.1
![screenshot 49](https://user-images.githubusercontent.com/40912417/42415619-9d05e566-8209-11e8-9a0c-a0386fc28d8d.jpg)

**Comment by Antecer** [comment]
Try to run the app using win7 compatibility mode, can it fix the problem?

**Comment by EvanSux** [comment]
I just tried win7. Still crashes.

**Comment by EvanSux** [comment]
Is there a way to reflash the firmware on the keypad?

**Comment by Antecer** [comment]
This issue has nothing to do with the firmware, just the app.

**Comment by Antecer** [comment]
Update App to version 1.3.2.4 can fixed it!
