### ISSUE TITLE
osu keyboard pressed twice in one press

### ISSUE THREAD

**Issue by CXwudi** [Antecer/AmusingKeypad#4]
sometime when I press the left button once, it actually pressed twice, not only in OSU, but also when you are typing on Word with osu keyboard.

**Comment by VaddyO** [comment]
Go into the AmusingKeypad software (which you can find here https://github.com/Antecer/AmusingKeypad/tree/master/Output/Application) and set the KeyDebounce to 50 or so like this
![this](https://user-images.githubusercontent.com/42323244/44004955-9a3a5db6-9e6b-11e8-822c-90538e4be98a.JPG)

**Comment by CXwudi** [comment]
Nice, Well fixed. thanks so much 👍
