### ISSUE TITLE
Device Linking...

### ISSUE THREAD

**Issue by Placepolter** [Antecer/AmusingKeypad#5]
i already redownloaded the program but still nothing happens
![device linking](https://user-images.githubusercontent.com/43908400/46571635-b1243a00-c978-11e8-9715-81280e9c32e5.png)

**Comment by Antecer** [comment]
Do your keypad work normal?

**Comment by Placepolter** [comment]
> Do your keypad work normal?

yes but i also have the double click in one click problem

**Comment by Antecer** [comment]
Come here please: https://discord.gg/3PVnNGu
Then we can talk faster.

**Comment by Placepolter** [comment]
> Come here please: https://discord.gg/3PVnNGu
> Then we can talk faster.

ok

**Comment by Antecer** [comment]
Incompatible USB3.0 driver.
Change the USB3.0 driver to fixed it, or use another usb2.0 port.
