### ISSUE TITLE
Not compatible with iPad

### ISSUE THREAD

**Issue by xmcp** [Antecer/AmusingKeypad#6]
iPad Pro 2018 allows external keyboards with a USB-C port. However, I found that my AmusingKeypad Pro cannot work well with it.

- If I connect the keypad to iPad with a USB-C to USB-C connector, nothing will happen.
- If I connect the keypad to iPad with a USB-A dongle, the LED will show up and iPad will detect the keyboard. However, the key mapping is incorrect so that pressed keys will be different with what I have configured.

I know that AmusingKeypad mainly targets Windows PC, but osu!lazer, the upcoming version of osu!, does support iOS platform, so hopefully this product can be used on iPad.

-----

Version information:

- AmusingKeypad Pro firmware v1.3.0.9
- Configuration program v1.3.5.5
- iPad Pro 2018 running iOS 12.1.1

**Comment by Antecer** [comment]
Sorry, I don't have an IOS device, so I don't know why the USB keyboard causes incorrect button mapping on iOS devices.

**Comment by Mic238** [comment]
Hi there,

I also found this issue, not on a iPad but on a Mac, I set zx under windows and it reads 8 and 6 on Mac. I think there might be a problem with multiple key strokes that iOS and Mac can't read.

EDIT: Z - 8, X - 6, ` - Not recognise, space - Not recognise, esc - /, there are some mapping inconsistency on Windows and Mac/iOS. Also both bootcamp Windows and virtual box Windows can recognise the correct key, if the keyboard is directly connect to Windows. (In VirtualBox, there is a setting that can connect USB device to Mac or Windows, if it's Mac it reads 8/6, if connect to windows, that's correctly read z/x.)

**Comment by Antecer** [comment]
So, @Mic238 mean i can use VirtualBox to test it?

**Comment by Mic238** [comment]
> So, @Mic238 mean i can use VirtualBox to test it?

I think so if you can get MacOS running in virtual box, might be a hard thing to do. The issue only comes up after upgrade the firmware to 2.0.0.3, it was fine on 1.3.0.whatever. I also tested on linux (raspiberry pi/raspibian/debian) without an issue.

In the mean time I just use karabiner to map the correct key, but there's no key mapping on iOS. And I found the keyboard is recognised as two separate devices, a mouse and a keyboard, could this be an issue?

```
{
        "device_id": 4294973184,
        "is_karabiner_virtual_hid_device": false,
        **"is_keyboard": true,
         "is_pointing_device": false,**
        "location_id": 336592896,
        "manufacturer": "Antecer",
        "product": "AmusingKeyPadK5",
        "product_id": 4108,
        "transport": "USB",
        "vendor_id": 28
    },
    {
        "device_id": 4294973190,
        "is_karabiner_virtual_hid_device": false,
        **"is_keyboard": false,
        "is_pointing_device": true,**
        "location_id": 336592896,
        "manufacturer": "Antecer",
        "product": "AmusingKeyPadK5",
        "product_id": 4108,
        "transport": "USB",
        "vendor_id": 28
    },
```

I found the key code table from apple developer website, which might be useful as well [Apple Developer](https://developer.apple.com/library/archive/technotes/tn2450/_index.html )

**Comment by Antecer** [comment]
@Mic238 
Yes, this keyboard has the function of a mouse at the same time, so you can see the keyboard and mouse devices from the computer side.
Where did you found the key code table, please upload it or tell me the download link.

**Comment by Mic238** [comment]
> @Mic238
> Yes, this keyboard has the function of a mouse at the same time, so you can see the keyboard and mouse devices from the computer side.
> Where did you found the key code table, please upload it or tell me the download link.

https://developer.apple.com/library/archive/technotes/tn2450/_index.html

**Comment by Antecer** [comment]
Yes, i used the key code table as the same of your link.
I think you can check "Script Key Remap".

**Comment by Mic238** [comment]
Microsoft Key table here https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, found something:

Windows Z (0x5A) - Mac 8 (0x25)
Windows X (0x58) - Mac 6 (0x23)
Windows Q (0x51) - Mac Y (0x1C)
Windows W (0x57) - Mac 5 (0x22)
Windows S (0x53) - Mac 1 (0x1E)

Clearly the offset is 0x35,
but Windows Esc (0x1B) - 0x35 = ??? and map to Mac backslash \ (0x31) which is not right.

**Comment by Antecer** [comment]
the Virtual-Key Codes not hid keycode, It is just a set of encoding mapping customized by the windows system, and has nothing to do with HID keycode.

The AmusingKeypad created by this keycode table:
[HIDKeyCodeTable.pdf](https://github.com/Antecer/AmusingKeypad/files/4605214/HIDKeyCodeTable.pdf)

**Comment by Mic238** [comment]
I'm just giving out an idea what might be happened, apparently this was not an issue on older firmware, is there a way to downgrade the firmware back to 1.3.0.x so @xmcp can use?

EDIT: I just realised he's on 1.3.0.9 already so maybe this is not a solution. That might be os version related then, coz I haven't use it for a while and im pretty sure it works fine on 10.13-10.14

**Comment by Antecer** [comment]
sorry, i removed the old firmware ...
and can't find it.

**Comment by Antecer** [comment]
Update the Firmwave to ver 3.0.0.2, it will can work on MacOS
