### ISSUE TITLE
Device Linking...

### ISSUE THREAD

**Issue by impicklepick** [Antecer/AmusingKeypad#7]
Just got my keypad and downloading the .exe file and ran it. It is stuck on device linking... I have it plugged in and it is all lit up.

**Comment by ilramen** [comment]
1. Try a different USB Port
2. Are you using the included USB-C Cable ? If not try the one that was included.
3. Since you just got the Keypad you need the Pro Application.

**Comment by impicklepick** [comment]
The front two (and most accessible) ports didn't work for it but the ones on the back of my computer worked. Now the cord is too short to reach. Looks like I'll have to figure out some position to make it reach or get a longer cord.
