### ISSUE TITLE
Problem with amusing keypad

### ISSUE THREAD

**Issue by DrTrouserPlank** [Antecer/AmusingKeypad#8]
My keypad used to work fine along with the amusing keypad program, but now I am no longer able to interact with the amusing keypad program. Depending on what order I connect things or activate the program one of several things happens.

1. If I connect the keypad and then click on the program, it appears on the taskbar but cannot be maximised. If you start another instance of the program you get an error. "the process cannot access the file because it is being used by another program"

2. If I open the program first it appears on screen as normal and says there is no device linked. Connecting the keypad however makes the program window freeze, it cannot be moved or interacted with it also does not recognise that the device is connected.. Disconnecting the keypad allows the window to be moved again.

The functioning of the keypad is strange. The two main buttons work with the customs binds I gave them when I last go into the program. The center of the 3 additional buttons also works with the custom bind I assigned it. The outer 2 buttons do not work/have been unbound.

Can you think of any way to get this working like it used to again?

**Comment by DrTrouserPlank** [comment]
well... I solved it by changing which usb port I am using. 

Very odd.

**Comment by Antecer** [comment]
Nice to see that your problem has been solved.
