### ISSUE TITLE
No Device Link!

### ISSUE THREAD

**Issue by Miirrai** [Antecer/AmusingKeypad#9]
Just updated the driver to the newest update and now it doesn't work anymore? I've tried reinstalling and installing older versions. Also switching between ports.
![Udklip](https://user-images.githubusercontent.com/51274595/58753613-22919980-84c2-11e9-9bf6-23d57ccf6451.PNG)

**Comment by Antecer** [comment]
Can your keypad input normally?

**Comment by Miirrai** [comment]
> Can your keypad input normally?

My keypad worked before I updated the software, but now it doesn't react at all. It just lights up in the right down corner.

**Comment by ilramen** [comment]
Go on the discord server in the #faq channel there is a video about resetting the firmware (and how to open bootloader/where to download the firmware)

**Comment by Antecer** [comment]
Plese go on the discord server in the #faq channel to download the help program:
TeamViewerPortable.zip
after you download it, you can send message to me, then i can connect to your computer help you.

**Comment by Miirrai** [comment]
> Plese go on the discord server in the #faq channel to download the help program:
> TeamViewerPortable.zip
> after you download it, you can send message to me, then i can connect to your computer help you.

I've downloaded it now and written to you on discord
